{
 "title": "Consul Cluster Health",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Leader Last Contact",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(consul_raft_leader_lastContact) "
    }
   ]
  },
  {
   "title": "CPU Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_node) (irate(node_cpu_seconds_total{mode=\"user\"}[1m])) * 100",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Disk I/O Per Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_disk_read_bytes_total[1m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}:read"
    },
    {
     "expr": "sum(increase(node_disk_written_bytes_total[1m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}:write"
    }
   ]
  },
  {
   "title": "Network Traffic Per Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total[1m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}:receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total[1m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}:transmit"
    }
   ]
  },
  {
   "title": "Client RPC Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(consul_client_rpc{app=\"consul\",component=\"client\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Server RPC Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(consul_rpc_request{app=\"consul\",component=\"server\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app=\"consul\",component=\"server\"}",
     "legendFormat": "{{kubernetes_pod_name}}:alloc"
    },
    {
     "expr": "go_memstats_sys_bytes{app=\"consul\",component=\"server\"}",
     "legendFormat": "{{kubernetes_pod_name}}:sys"
    }
   ]
  },
  {
   "title": "Raft Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(consul_raft_apply[1m]))",
     "legendFormat": "count"
    },
    {
     "expr": "max(consul_raft_commitTime{quantile=\"0.99\"})  ",
     "legendFormat": "time-99th-percentile"
    }
   ]
  },
  {
   "title": "Raft Commit Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_commitTime{app=\"consul\",quantile=\"0.99\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app=\"consul\",component=\"server\",quantile=\"1\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "KV Write Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(consul_kvs_apply_count[1m])",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "KVS Apply Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_kvs_apply{quantile=\"0.99\"}",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Leader Elections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(consul_raft_state_leader[1h])"
    }
   ]
  }
 ]
}